const fs = require('fs'); const path = require('path'); const initSqlJs = require('sql.js'); const crypto = require('crypto');
let db; let file;
async function init(dataDir) { const SQL = await initSqlJs({ locateFile: (f) => path.join(__dirname, '../node_modules/sql.js/dist', f) }); file = path.join(dataDir, 'supplier-reconciliation.sqlite'); db = fs.existsSync(file) ? new SQL.Database(fs.readFileSync(file)) : new SQL.Database(); db.run(`CREATE TABLE IF NOT EXISTS bills (id INTEGER PRIMARY KEY AUTOINCREMENT, sync_id TEXT UNIQUE, posting_date TEXT, bill_date TEXT, supplier_name TEXT, supplier_bill_no TEXT, voucher_no TEXT, total_bill_amount REAL, tax_percent REAL, tax_amount REAL, actual_amount REAL, category TEXT DEFAULT 'PAYABLE', remarks TEXT, deleted_at TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS payments (id INTEGER PRIMARY KEY AUTOINCREMENT, sync_id TEXT UNIQUE, bill_sync_id TEXT, payment_date TEXT, amount REAL, payment_mode TEXT, reference_no TEXT, remarks TEXT, deleted_at TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);`); save(); }
function save() { fs.writeFileSync(file, Buffer.from(db.export())); }
function rows(sql, params = []) { const stmt = db.prepare(sql); stmt.bind(params); const out=[]; while(stmt.step()) out.push(stmt.getAsObject()); stmt.free(); return out; }
const one = (sql,p=[]) => rows(sql,p)[0] || null; const money = n => Math.round((Number(n)||0)*100)/100;
function saveBill(x) { const total=money(x.total_bill_amount), tax=Number(x.tax_percent)||0, taxAmount=money(total*tax/100), actual=money(total-taxAmount), sync=x.sync_id||crypto.randomUUID(); const existing=one('SELECT id FROM bills WHERE sync_id=?',[sync]); const vals=[x.posting_date,x.bill_date,x.supplier_name,x.supplier_bill_no||'',x.voucher_no||'',total,tax,taxAmount,actual,x.category||'PAYABLE',x.remarks||'',sync]; if(existing) db.run('UPDATE bills SET posting_date=?,bill_date=?,supplier_name=?,supplier_bill_no=?,voucher_no=?,total_bill_amount=?,tax_percent=?,tax_amount=?,actual_amount=?,category=?,remarks=? WHERE sync_id=?',vals); else db.run('INSERT INTO bills(posting_date,bill_date,supplier_name,supplier_bill_no,voucher_no,total_bill_amount,tax_percent,tax_amount,actual_amount,category,remarks,sync_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',vals); save(); return one('SELECT * FROM bills WHERE sync_id=?',[sync]); }
function addPayment(x) { const sync=x.sync_id||crypto.randomUUID(); db.run('INSERT OR REPLACE INTO payments(sync_id,bill_sync_id,payment_date,amount,payment_mode,reference_no,remarks) VALUES(?,?,?,?,?,?,?)',[sync,x.bill_sync_id,x.payment_date,money(x.amount),x.payment_mode||'',x.reference_no||'',x.remarks||'']); save(); return one('SELECT * FROM payments WHERE sync_id=?',[sync]); }
function remove(table,id) { const item=one(`SELECT * FROM ${table} WHERE sync_id=?`,[id]); db.run(`UPDATE ${table} SET deleted_at=CURRENT_TIMESTAMP WHERE sync_id=?`,[id]); save(); return item; }
function list(f={}) { let where='b.deleted_at IS NULL', p=[]; if(f.from){where+=' AND b.posting_date>=?';p.push(f.from)} if(f.to){where+=' AND b.posting_date<=?';p.push(f.to)} const bills=rows(`SELECT b.* FROM bills b WHERE ${where} ORDER BY posting_date DESC,id DESC`,p); const payments=rows('SELECT * FROM payments WHERE deleted_at IS NULL'); return bills.map(b=>{const linked=payments.filter(x=>x.bill_sync_id===b.sync_id);const paid=money(linked.reduce((s,x)=>s+Number(x.amount),0));const excluded=b.category!=='PAYABLE';const remaining=excluded?0:money(Math.max(0,b.actual_amount-paid));return {...b,payments:linked,paid_amount:paid,remaining_balance:remaining,payment_status:excluded?b.category:paid===0?'UNPAID':remaining>0?'PARTIAL':paid>b.actual_amount?'OVERPAID':'COMPLETE'}}); }
module.exports={init,saveBill,addPayment,list,deleteBill:id=>remove('bills',id),deletePayment:id=>remove('payments',id),names:()=>rows('SELECT DISTINCT supplier_name FROM bills WHERE deleted_at IS NULL ORDER BY supplier_name').map(x=>x.supplier_name)};
